from selenium import webdriver
driver = webdriver.Chrome()
driver.get('https://www.seleniumeasy.com/test/basic-first-form-demo.html')
messageField = driver.find_element_by_xpath('//*[@id="user-message"]')
messageField.send_keys('Hello world!!!!!!!!')
button = driver.find_element_by_xpath('//*[@id="get-input"]/button')
button.click()
# driver.execute_script("arguments[0].click();", button)
a = driver.find_element_by_xpath('//*[@id="sum1"]')
b = driver.find_element_by_xpath('//*[@id="sum2"]')
totalButton = driver.find_element_by_xpath('//*[@id="gettotal"]/button')
a.send_keys('35')
b.send_keys('30')
totalButton.click()